services:
  database:
    container_name: postgres
    image: postgres:16.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=posts
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data:
